### ISSUE TITLE
Filter Relationship

### ISSUE THREAD

**Issue by masitings** [abbasudo/laravel-purity#23]
Hi there!

Thanks for this awesome package, i really like to use it however, im facing the issues when i do some implementation. It cannot filter the relationship as you were explain in the videos. id like to use it in $contains approach, here are my code. The idea is i wanted to filter the member by its phone_number field. 

![image](https://github.com/abbasudo/laravel-purity/assets/29356430/0b1a63ce-9be4-4da1-9cf6-1780bead54e8)

![image](https://github.com/abbasudo/laravel-purity/assets/29356430/c8091604-39f9-48c9-9d19-8d91697cb286)

DATA FILTERED
![image](https://github.com/abbasudo/laravel-purity/assets/29356430/d8f882a6-717e-4fa9-8fa8-ef37a5e9dc9a)

DATA UNFILTERED
![image](https://github.com/abbasudo/laravel-purity/assets/29356430/fe2453be-8bd2-45d0-a9fb-dcf73684ba47)

As you can see, there are member with phone_number 17.

**Comment by abbasudo** [comment]
Hello, @masitings. glad to hear that purity helped you.
everything seems to be alright from here.
make sure you added `Filterable` trait in both `User` and `Member` classes.
if you did so and still didn't get anything, provide me with a detailed error by changing silent variable to false in `purity.php` config file.

**Comment by masitings** [comment]
Hi @abbasudo

This is the message that i got when i set the silent variable to false. Im guessing that the error was something about relation that User cannot get the Member right ? I also attached my model in here whic 1 User can only have 1 Member.


![image](https://github.com/abbasudo/laravel-purity/assets/29356430/1244ed05-f98d-440d-a5d6-5648e5460f32)

User model
![image](https://github.com/abbasudo/laravel-purity/assets/29356430/e57eaba8-3bc1-47d7-853c-f4efb7df718a)

Member model
![image](https://github.com/abbasudo/laravel-purity/assets/29356430/f411a5be-d58c-4ac4-9da2-87c0dee363f6)

**Comment by abbasudo** [comment]
oh thats actually a problem with the package. it only considers `hasMany` relations in the allowed fields.
this issue will be fixed in the next update.
however, to quickly solve this problem by yourself add this variable to your `User` model in order to overwrite allowed fields.
```php
protected $filterFields = [
    'first_name',
    'last_name',
    'email',
    'member',
    // etc ...
];
```

**Comment by abbasudo** [comment]
hasOne relations do not extend Relation model directly so we have a problem identifying them in [this line](https://github.com/abbasudo/laravel-purity/blob/28c058bb94775462577f29174c38e1a3eafa9b27/src/Traits/Filterable.php#L119C64-L119C64)

any PR to fix this will be accepted

**Comment by masitings** [comment]
i see, another questions.. So, actually the Member has relation with Tier too, do you think with that kind of approach i can put the fiilterFields there by using 'member.tier' or i need to put the hasManyThrough relationship to be able to put in there ?

**Comment by abbasudo** [comment]
> i see, another questions.. So, actually the Member has relation with Tier too, do you think with that kind of approach i can put the fiilterFields there by using 'member.tier' or i need to put the hasManyThrough relationship to be able to put in there ?

hasManyThrouth extends Relation so you are fine. however you should define `filterFields` with tier in `Member` class to overwrite allowed fields of Members

**Comment by masitings** [comment]
@abbasudo noted! Thanks, well helped!

**Comment by abbasudo** [comment]
@masitings Glad to help. feel free to open issues anytime.

**Comment by Lakshan-Madushanka** [comment]
You must define return type in relationship methods in order to package to identify them as allowed fields by default.

**Comment by alansgonzaga** [comment]
Hello, I'm struggling with some relationship filters. In short, I'm having trouble filtering relationships (One to Many (Polymorphic) [morphTo]). I did a lot of debugging of the SQL query that was being executed and I saw that the morphTo relationship was never used. So I came here to look for issues, and I believe it seems to be related to this issue. I saw that they said that the HasOne relationship is also not recognized. Since they said that this would be fixed in the future, I did some tests here with a HasOne, but I don't think it works yet, right?

I refactored my production environment to use purity filters, and I'd like to take this opportunity to say that the package is amazing. Unfortunately, I didn't notice that this type of relationship stopped working. It used to work with my old strategy (https://github.com/savannabits/primevue-datatables).

I've tried with and without filling in the $filterFields, I've also made sure that all relationships have the return type filled in, and the Models use the Filterable trait.

I'd like to check if I'm doing something wrong or if it really is a current limitation?

![image](https://github.com/user-attachments/assets/69302c83-52ab-486c-a708-5f39288719a1)
![image](https://github.com/user-attachments/assets/361448c9-482d-42e8-9843-e13a2ca9007d)
![image](https://github.com/user-attachments/assets/8910edd6-fd35-477b-ae7d-895d3d16a4eb)
![image](https://github.com/user-attachments/assets/cf4e1cda-4d5a-4657-a5c4-f32aa5c2afd5)
